### ISSUE TITLE
Moving Site from GitHub/philanderson888 repository

### ISSUE THREAD

**Issue by jibbylt** [jibbylt/revival-direct-coaches#1]
Moving the site to a GitHub repository owned by the site owner

**Comment by jibbylt** [comment]
Moving the DNS records.

Here are the existing DNS records at GitHub/philanderson888


DNS settings
Manage the Domain Name System (DNS) settings for this domain. Learn more

## DNS records

### email

revivaldirectcoaches.co.uk
3600
IN
MX
1 
ASPMX.L.GOOGLE.COM.

revivaldirectcoaches.co.uk
3600
IN
MX
5 
alt1.aspmx.l.google.com.

revivaldirectcoaches.co.uk
3600
IN
MX
5 
ALT2.ASPMX.L.GOOGLE.COM.

revivaldirectcoaches.co.uk
3600
IN
MX
10 
ALT3.ASPMX.L.GOOGLE.COM.

revivaldirectcoaches.co.uk
3600
IN
MX
10 
ALT4.ASPMX.L.GOOGLE.COM.


### www

revivaldirectcoaches.co.uk
3600
IN
NETLIFY
nervous-kare-6ec113.netlify.com

www.revivaldirectcoaches.co.uk
3600
IN
NETLIFY
nervous-kare-6ec113.netlify.com

**Comment by jibbylt** [comment]
Tried to move site over to new Netlify but says site already owned so will have to wait for the disconnect I think.

**Comment by philanderson888** [comment]
Site has been updated so it is now fully owned and managed by Jibby and all data is completely within the realm of Jibby.

Test email sent also - need to verify it is working

**Comment by jibbylt** [comment]
Hi, I

Have no clue of how to log in or do anything.  Can you show me how to do
this?

Jibby

**Comment by philanderson888** [comment]
Sure.

First log in to GitHub.com with your email and password I will send you by WhatsApp

Sent from my iPhone

On 7 Jun 2020, at 16:56, jibbylt <notifications@github.com> wrote:

﻿

Hi, I

Have no clue of how to log in or do anything. Can you show me how to do
this?

Jibby

**Comment by philanderson888** [comment]
This has now been completed and also the emails are now pointing to the new location RevivalDirect.co.uk and being dealt with in GSuite

**Comment by philanderson888** [comment]
Closed and all working now including both the site and the emails.
