### ISSUE TITLE
Time Log and Blog Of Work Completed

### ISSUE THREAD

**Issue by philanderson888** [jibbylt/revival-direct-coaches#10]

**Comment by philanderson888** [comment]
19 July 2020

Spent from 1240 to 220pm looking at the overview and plan for the new website.

Also added white to terms and conditions

Also added google maps to home page

**Comment by philanderson888** [comment]
Also spent about the same last week on a Skype call also

**Comment by philanderson888** [comment]
Sunday 26 July 2020

Started around 1230pm 

Created the new menu with also having drop-down items

Started to delete content from pages before building them back up again

Also edited the title from PERSONAL to REVIVAL DIRECT - getting you there

Also updated the Copyright at the footer

**Comment by philanderson888** [comment]
Also managed to strip down the website to nothing so all of the pages are blank, also stripped down the footer and minimalised all the menus etc.

Total time today 2 hours from 1230 to about 3pm

**Comment by philanderson888** [comment]
From: Philip Anderson 
Sent: 26 July 2020 15:49
To: 'REVIVAL DIRECT' <enquiries@revivaldirect.co.uk>
Subject: Progress on RevivalDirect 26 July 2020

1.	Stripped down the website so it’s just minimalistic – nothing on any of the pages
2.	Edited the Logo so it reads REVIVAL DIRECT GETTING YOU THERE
3.	Added copyright to the footer
4.	Removed the sidebar for now

That’s in addition to the work we did together which was just add all the menu items and sub-menu items.

Site is now clean and ready to build

Time taken today : around 2 hours.

Thanks and God bless Jibby

Phil


On your part send me

1.	Terms And Conditions

**Comment by philanderson888** [comment]
Total at least 3 sessions  = 6+ hours

**Comment by jibbylt** [comment]
### Time Log
26 July 2 hours

Sunday 9 Aug 2020 2PM Beginning Work - call with Jibby
1.5 hours total exploring Elementor - how to create pages, effects, image galleries, headings, social media, pages, forms etc and looking at the differences between the free and paid options.

**Comment by jibbylt** [comment]
### Google Analytics

Checking out the google analytics for revivaldirectcoaches.co.uk

There were 73 visitors over the last 90 days

https://analytics.google.com/analytics/web/?pli=1&authuser=2#/report-home/a151935712w214919214p205513765

**Comment by philanderson888** [comment]
Doing a little more work to try and get the website started properly today.

Just maybe have a look at the home page and see if I can get a theme and a design going and looking nice.

Either build from scratch or try and import some styling - I think I have the basic styling already so am looking to just build from scratch here and see how it goes.

**Comment by philanderson888** [comment]
545pm starting work and just having a look at basics

**Comment by philanderson888** [comment]
830pm update on Saturday 5 September 2020

See the Issue 6 - Get the theme going - for an update on what I have done so far this afternoon.  https://github.com/jibbylt/revival-direct-coaches/issues/6

Basically 1) Images and sourcing new ones 2) Removing existing media images 3) Tidying up the site and removing all items from the previous template which were getting in the way of building a new site 4) Checking pages and URLs all work and interlink properly on the main menu.

That's it so far - still working though.

**Comment by jibbylt** [comment]
Hello ,

I thought we agreed the Ocean view would work, why are we looking for a new theme? I am a little confused. We already agreed a theme.

Jibby
________________________________

**Comment by philanderson888** [comment]
Getting up early this morning to see if I can do a push on this website today.   630am starting work.

**Comment by philanderson888** [comment]
Did about 3 hours yesterday - see if I can get a basic look and feel going today.

**Comment by philanderson888** [comment]
Finished for now - have done about 2-3 hours today just getting the main page looking a bit better, sorting out the full screen display of the main image, getting some basic text on the main header screen, and completing a basic contact form and testing out that it actually works.

Pages worked on

![image](https://user-images.githubusercontent.com/8657188/92324712-310f1f00-f03c-11ea-9759-9e5194e59844.png)

![image](https://user-images.githubusercontent.com/8657188/92324726-471cdf80-f03c-11ea-98b0-b9f6790bd45c.png)
